arch:
  - arm64

services: #services allow to access cmd
# could add db as well
  - docker

before_install: 
 - docker build image -t ${IMAGE_NAME} .

script: 
  - docker run -d -p 3000:3000 ${IMAGE_NAME}

after_success: 
 - docker login -u ${DOCKERHUB_USERNAME} -p ${$DOCKERHUB_PASSWORD}
 - docker tag ${IMAGE_NAME} marawanzz/${IMAGE_NAME}:latest
 - docker push marawanzz/${IMAGE_NAME}:latest