version: '3.7'
services:
  food-app-backend:
    depends_on:
      - db
    container_name: food-app-backend
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
      - /app/node_modules
    env_file: ./.env

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db:/var/lib/postgresql/data
    env_file: ./.env

volumes:
  db:
    driver: local
